name: Discord Notification


on: [push, issues, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'A new commit has been pushed to X-ProxyTech/Ideas.'
