name: Discord Notification
on: [issue_comment, issues]
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
      with:
        args: 'A new Idea has been commited to X-ProxyTech/Ideas.'
    - name: Discord notification
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
      uses: Ilshidur/action-discord@master
